---
## Provided by Playbook

proxmox_api_host: ""
proxmox_api_user: ""
proxmox_api_password: ""
proxmox_network_lan: ""
virtual_machine_cores: 2
virtual_machine_id: auto
virtual_machine_memory: 2048
virtual_machine_name: testvm
virtual_machine_password: debian

## Other, may be overridden in Playbook

proxmox_volume_group: mpio
proxmox_template_url: ""
proxmox_template_name: debian-12-standard_12.2-1_amd64.tar.zst
proxmox_template_storage: nas
proxmox_template_type: vztmpl
virtual_machine_disksize: 8
virtual_machine_features:
  - mount=cifs;nfs
  - nesting={{ 1 if virtual_machine_unprivileged else 0 }}
virtual_machine_mounts: []
  # - id: mp0
  #   storage: "{{ proxmox_volume_group }}"
  #   size: 8
  #   mount_point: "/mnt/data1"
  #   acl: false                     # Optional.
  #   backup: false                  # Optional.
  #   quota: false                   # Optional.
  #   read_only: false               # Optional.
  #   skip_replication: false        # Optional.
virtual_machine_nameserver: "{{ vars[proxmox_network_lan].dnsservers }}"
virtual_machine_network:
  - id: net0
    name: eth0
    ip4: "ip={{ 'dhcp' if virtual_machine_id == 'auto' else config_ip4 }}"
    ip6: "{{ '' if not vars[proxmox_network_lan].ip6 else config_ip6 }}"
virtual_machine_searchdomain: "{{ vars[proxmox_network_lan].searchdomain }}"
virtual_machine_start: true
virtual_machine_swap: 512
virtual_machine_unprivileged: false

## Computed Values

config_ip4: >-
    {{ virtual_machine_ip4 + '/' + vars[proxmox_network_lan].ip4_netmask
    | string + ',gw=' + vars[proxmox_network_lan].ip4_gateway }}
config_ip6: >-
  ip6={{ virtual_machine_ip6 }}/{{ vars[proxmox_network_lan].ip6_netmask
  | string }},gw6={{ vars[proxmox_network_lan].ip6_gateway }}
config_mounts: >-
  { {%- for item in virtual_machine_mounts -%}
  "{{ item.id }}":"{{ item.storage }}:{{ item.size }},mp={{ item.mount_point }}
  {% if item.acl is defined and item.acl %},acl=1{% else %},acl=0{% endif %}
  {% if item.quota is defined and item.quota %},quota=1{% endif %}
  {% if item.read_only is defined and item.read_only %},ro=1{% endif %}
  {% if item.backup is defined and item.backup %},backup=1{% endif %}
  {% if item.skip_replication is defined and item.skip_replication %},replicate=0{% endif %}",
  {%- endfor -%} }
config_net: >-
  { {%- for item in virtual_machine_network -%}
  "{{ item.id }}":"name={{ item.name }},bridge=vmbr{{ vars[proxmox_network_lan].vmbr }},
  {% if (item.ip4 is defined) %}{{ item.ip4 }},{% endif %}
  {% if (item.ip6 | length > 0) %}{{ item.ip6 }},{% endif %}
  tag={{ vars[proxmox_network_lan].tag }}"
  {%- endfor -%} }
config_ostemplate: "{{ proxmox_template_storage }}:{{ proxmox_template_type }}/{{ proxmox_template_name }}"
ssh_keys: "{{ lookup('ansible.builtin.file', 'sshpub/' + virtual_machine_name + '.key.pub', errors='ignore') }}"
virtual_machine_hex: "{{ '%04x' | format((virtual_machine_int | int * virtual_machine_int | int) | int) }}"
virtual_machine_int: "{{ 1 if virtual_machine_id == 'auto' else (virtual_machine_id | string)[-3:] | int }}"
virtual_machine_ip4: "{{ vars[proxmox_network_lan].ip4_prefix }}.{{ virtual_machine_int }}"
virtual_machine_ip6: >-
    {{ '' if not vars[proxmox_network_lan].ip6 else vars[proxmox_network_lan].ip6_prefix + '::'
    + virtual_machine_hex }}
